language: node_js
node_js:
- '10'

script: npx redoc-cli bundle schema/collectingEvent.yml -o redoc/index.html

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN 
 local_dir: redoc
 keep_history: true
 on:
  branch: master
  
