openapi: 3.0.0
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/AAFC/test/1.0.0
info:
  description: Used to organize material samples according to some organizational theme.
  version: "1.0.0"
  title: Assemblage schema
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /v1/assemblage:
    get:
      tags:
        - Assemblage
      summary: Get assemblage
      operationId: getAssemblages
      description: By passing in query string, user can get available assemblages authorised
      parameters:
        - in: query
          name: filter[rsql]
          description: pass an optional search string for looking up the assemblages
          schema:
            type: string
        - in: query
          name: sort
          description: optional sort order string, such as descending, denoted by "-"
          schema:
            type: string
        - in: query
          name: page[offset]
          description: number of records to skip when paging
          schema:
            type: integer
            format: int32
        - in: query
          name: page[limit]
          description: maximum number of records to return when paging
          schema:
            type: integer
            format: int32
            minimum: 0
            maximum: 50
      responses:
        '200':
          description: assemblages satifying the query restrictions
          content:
            application/vnd.api+json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/Assemblage'                
        '404':
          description: assemblage not found
    post:
      tags:
        - Assemblage
      summary: Add assemblage
      operationId: addAssemblage
      description: Adds a assemblage
      responses:
        '201':
          description: Assemblage created
        '422':
          description: Data integrity violation          
      requestBody:
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/NewAssemblage'
        description: Assemblage to add
  /v1/assemblage/{Id}:
    get:
      tags:
        - Assemblage
      summary: Find assemblage by ID
      description: Returns a single assemblage
      operationId: getAssemblageById
      parameters:
        - name: Id
          in: path
          description: ID of assemblage to return
          required: true
          schema:
            type: string
            format: uuid            
      responses:
        '200':
          description: successful operation
          content:
            application/vnd.api+json:
              schema:          
                $ref: '#/components/schemas/Assemblage'
        '400':
          description: Not a valid uuid                
        '404':
          description: Assemblage not found          
    patch:
      tags:
        - Assemblage
      summary: Update assemblage
      operationId: updateAssemblage
      description: update a assemblage
      parameters:
        - name: Id
          in: path
          description: Assemblage id to patch
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Assemblage updated
        '400':
          description: invalid input, object invalid
      requestBody:
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/Assemblage'
        description: Assemblage to add
    delete:
      tags:
        - Assemblage
      summary: Delete assemblage
      operationId: deleteAssemblage
      description: delete an assemblage
      parameters:
        - name: Id
          in: path
          description: Assemblage id to delete
          required: true
          schema:
            type: string
            format: uuid            
      responses:
        '200':
          description: Assemblage marked as deleted
        '400':
          description: Not a valid uuid          
        '404':
          description: Assemblage not found       
components:
  schemas:
    Assemblage:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
          properties:
            id:
              type: string
              format: uuid
              example: d290f1ee-6c54-4b01-90e6-d701748f0851
              description: Identifier of the object as UUID
          allOf:
            - $ref: '#/components/schemas/CommonAssemblage'

    NewAssemblage:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          allOf:
            - $ref: '#/components/schemas/CommonAssemblage'

    CommonAssemblage:
      type: object
      required:
        - type
        - attributes       
      properties:            
        type:
          enum: [assemblage]      
          description: The type of data being returned.
        attributes:
          type: object
          properties:
            name:
              type: string
              description: The name of the assemblage
            createdBy:
              type: string      
              readOnly: true
              description: authenticated user who create the assemblage
            createdOn:              
              type: string
              format: date-time                            
              readOnly: true
              description: date and time when the assemblage was created in ISO format
              example: 1985-04-12T23:20:50.52Z
            group:
              type: string
              description: The group in which the assemblage belongs to
            managedAttributes:
              type: object
              description: The manage attributes, map of key/value pair. Patch Strategy is SET so the entire managedAttributes needs to be rebmit on PATCH/PUT.
              additionalProperties:
                type: string
            multilingualDescription:
              type: object
              nullable: true
              properties:
                descriptions:
                  type: array
                  nullable: true
                  items:
                    type: object
                    properties:
                      lang:
                        type: string
                        description: language of the description
                      desc:
                        type: string
                        description: the description
        relationships:
          type: object
          nullable: true
          properties:
            attachment:
              type: object
              nullable: true
              properties:
                data:
                  type: array
                  items:
                    type: object
                    required:
                      - type
                      - id
                    properties:
                      type: 
                        type: string
                        example: metadata
                      id:
                        type: string
                        format: uuid
                        description: Unique identifier metadata for the resource
                        example: 8f68a05f-937d-4d40-88b4-ed92720d9c3f
