openapi: 3.0.0
servers:
  - description: DINA - AAFC
    url: https://virtserver.dina-aafc.com/AAFC/1.0.0
info:
  description: Collection API Schema
  version: "1.0.0"
  title: Collection Schema
  contact:
    email: dina-aafc@canada.ca
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
   
paths:
  /v1/collecting-event:
    $ref: 'collectingEvent.yml#/paths/~1v1~1collecting-event'
  /v1/collecting-event/{Id}:
    $ref: 'collectingEvent.yml#/paths/~1v1~1collecting-event~1{Id}'  



