openapi: 3.0.0
servers:
  - description: DINA - AAFC
    url: https://virtserver.dina-aafc.com/AAFC/1.0.0
info:
  description: Form Template schema
  version: "1.0.0"
  title: Form Template schema
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /v1/form-template:
    get:
      tags:
        - Form Template
      summary: Get Form Template
      operationId: getFormTemplates
      description: By passing in query string, user can get Form Template authorized
      parameters:
        - in: query
          name: sort
          description: optional sort order string, such as descending, denoted by "-"
          schema:
            type: string
        - in: query
          name: page[offset]
          description: number of records to skip when paging
          schema:
            type: integer
            format: int32
        - in: query
          name: page[limit]
          description: maximum number of records to return when paging
          schema:
            type: integer
            format: int32
            minimum: 0
            maximum: 50
      responses:
        '200':
          description: Form Template satifying the query restrictions
          content:
            application/vnd.api+json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/FormTemplate'
        '404':
          description: Form Template not found
    post:
      tags:
        - Form Template
      summary: AddForm Template
      operationId: addFormTemplate
      description: Adds a Form Template
      responses:
        '201':
          description: Form Template created
        '422':
          description: Data integrity violation          
      requestBody:
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/NewFormTemplate'
        description: Form Template to add
  /v1/form-template/{Id}:
    get:
      tags:
        - Form Template
      summary: Find Form Template by ID
      description: Returns a single Form Template
      operationId: geFormTemplateById
      parameters:
        - name: Id
          in: path
          description: ID of the Form Template to return
          required: true
          schema:
            type: string
            format: uuid            
      responses:
        '200':
          description: successful operation
          content:
            application/vnd.api+json:
              schema:          
                $ref: '#/components/schemas/FormTemplate'
        '400':
          description: Not a valid uuid                
        '404':
          description: Form Template not found
    patch:
      tags:
        - Form Template
      summary: Update Form Template
      operationId: updateFormTemplate
      description: Update a Form Template
      parameters:
        - name: Id
          in: path
          description: Form Template id to patch
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Form Template updated
        '400':
          description: invalid input, object invalid
      requestBody:
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/FormTemplate'
        description: Form Template to add
    delete:
      tags:
        - Form Template
      summary: Delete Form Template
      operationId: deleteFormTemplate
      description: delete a Form Template
      parameters:
        - name: Id
          in: path
          description: Form Template id to delete
          required: true
          schema:
            type: string
            format: uuid            
      responses:
        '200':
          description: Form Template deleted
        '400':
          description: Not a valid uuid          
        '404':
          description: Form Template not found
components:
  schemas:
    FormTemplate:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
          properties:
            id:
              type: string
              format: uuid
              example: d290f1ee-6c54-4b01-90e6-d701748f0851
              description: Identifier of the object as UUID
          allOf:
            - $ref: '#/components/schemas/CommonFormTemplate'

    NewFormTemplate:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          allOf:
            - $ref: '#/components/schemas/CommonFormTemplate'

    CommonFormTemplate:
      type: object
      required:
        - type
        - attributes       
      properties:
        type:
          enum: [form-template]
          description: The type of data being returned.
        attributes:
          type: object
          properties:
            name:
              type: string
              description: The name of the Form Template
            group:
              type: string
              description: The group in which the Form Template belongs to
            restrictToCreatedBy:
              type: boolean
              description: Is the Form Template restricted to the user represented by createdBY
            viewConfiguration:
              type: object
              description: Configuration object of the Form Template
            components:
              type: array
              items:
                type: object
              nullable: true
              description: List of components of the FormTemplate
            createdBy:
              type: string      
              readOnly: true
              description: authenticated user who create the Form Template
            createdOn:              
              type: string
              format: date-time                            
              readOnly: true
              description: date and time when the Form Template was created in ISO format
              example: 1985-04-12T23:20:50.52Z

