openapi: 3.0.0
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/AAFC/test/1.0.0
info:
  description: Material Sample Action Definition schema
  version: "1.0.0"
  title: Material Sample Action Definition schema
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /v1/material-sample-action-definition:
    get:
      summary: Get material sample action definition
      operationId: getMaterialSampleActionDefinitions
      description: By passing in query string, user can get available material sample action definitions authorised
      parameters:
        - in: query
          name: filter[rsql]
          description: pass an optional search string for looking up the material sample action definitions
          schema:
            type: string
        - in: query
          name: sort
          description: optional sort order string, such as descending, denoted by "-"
          schema:
            type: string
        - in: query
          name: page[offset]
          description: number of records to skip when paging
          schema:
            type: integer
            format: int32
        - in: query
          name: page[limit]
          description: maximum number of records to return when paging
          schema:
            type: integer
            format: int32
            minimum: 0
            maximum: 50
      responses:
        '200':
          description: material sample action definitions satifying the query restrictions
          content:
            application/vnd.api+json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/MaterialSampleActionDefinition'                
        '404':
          description: material sample action definition not found
    post:
      summary: Add material sample action definition
      operationId: addMaterialSampleActionDefinition
      description: Adds a material sample action definition
      responses:
        '201':
          description: material sample action definition created
        '422':
          description: Data integrity violation          
      requestBody:
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/NewMaterialSampleActionDefinition'
        description: MaterialSampleActionDefinition to add
  /v1/material-sample-action-definition/{Id}:
    get:
      summary: Find material sample action definition by ID
      description: Returns a single material sample action definition
      operationId: getMaterialSampleActionDefinitionById
      parameters:
        - name: Id
          in: path
          description: ID of material sample action definition to return
          required: true
          schema:
            type: string
            format: uuid            
      responses:
        '200':
          description: successful operation
          content:
            application/vnd.api+json:
              schema:          
                $ref: '#/components/schemas/MaterialSampleActionDefinition'
        '400':
          description: Not a valid uuid                
        '404':
          description: MaterialSampleActionDefinition not found          
    patch:
      summary: Update material sample action definition
      operationId: updateMaterialSampleActionDefinition
      description: update a material sample action definition
      parameters:
        - name: Id
          in: path
          description: material sample action definition id to patch
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: material sample action definition updated
        '400':
          description: invalid input, object invalid
      requestBody:
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/MaterialSampleActionDefinition'
        description: material sample action definition to add
    delete:
      summary: Delete material sample action definition
      operationId: deleteMaterialSampleActionDefinition
      description: delete a material sample action definition
      parameters:
        - name: Id
          in: path
          description: material sample action definition id to delete
          required: true
          schema:
            type: string
            format: uuid            
      responses:
        '200':
          description: material sample action definition marked as deleted
        '400':
          description: Not a valid uuid          
        '404':
          description: material sample action definition not found       
components:
  schemas:
    MaterialSampleActionDefinition:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
          properties:
            id:
              type: string
              format: uuid
              example: d290f1ee-6c54-4b01-90e6-d701748f0851
              description: Identifier of the object as UUID
          allOf:
            - $ref: '#/components/schemas/CommonMaterialSampleActionDefinition'

    NewMaterialSampleActionDefinition:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          allOf:
            - $ref: '#/components/schemas/CommonMaterialSampleActionDefinition'

    CommonMaterialSampleActionDefinition:
      type: object
      required:
        - type
        - attributes       
      properties:            
        type:
          enum: [material-sample-action-definition]      
          description: The type of data being returned.
        attributes:
          type: object
          properties:
            name:
              type: string
              description: The name of the material sample action definition
            createdBy:
              type: string      
              readOnly: true
              description: authenticated user who create the material sample action definition
            createdOn:              
              type: string
              format: date-time                            
              readOnly: true
              description: date and time when the material sample action definition was created in ISO format
              example: 1985-04-12T23:20:50.52Z
            group:
              type: string
              description: The group in which the material sample action definition belongs to