openapi: 3.0.0
servers:
  - description: DINA - AAFC
    url: https://virtserver.dina-aafc.com/AAFC/1.0.0
info:
  description: Collection API Schema
  version: "0.1.0"
  title: Collection Schema - DRAFT
  contact:
    email: dina-aafc@canada.ca
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
   
paths:
  /v1/collecting-event:
    $ref: 'collectingEvent.yml#/paths/~1v1~1collecting-event'
  /v1/collecting-event/{Id}:
    $ref: 'collectingEvent.yml#/paths/~1v1~1collecting-event~1{Id}'
  /v1/collection:
    $ref: 'collection.yml#/paths/~1v1~1collection'
  /v1/collection/{Id}:
    $ref: 'collection.yml#/paths/~1v1~1collection~1{Id}'
  /v1/collection-sequence-generator:
    $ref: 'collectionSequenceGenerator.yml#/paths/~1v1~1collection-sequence-generator'
  /v1/managed-attribute:
    $ref: 'collectionManagedAttribute.yml#/paths/~1v1~1managed-attribute'
  /v1/managed-attribute/{Id}:
    $ref: 'collectionManagedAttribute.yml#/paths/~1v1~1managed-attribute~1{Id}'
  /v1/material-sample:
    $ref: 'materialSample.yml#/paths/~1v1~1material-sample'
  /v1/material-sample/{Id}:
    $ref: 'materialSample.yml#/paths/~1v1~1material-sample~1{Id}'
  /v1/preparation-type:
    $ref: 'preparationType.yml#/paths/~1v1~1preparation-type'
  /v1/preparation-type/{Id}:
    $ref: 'preparationType.yml#/paths/~1v1~1preparation-type~1{Id}'
  /v1/preparation-method:
    $ref: 'preparationMethod.yml#/paths/~1v1~1preparation-method'
  /v1/preparation-method/{Id}:
    $ref: 'preparationMethod.yml#/paths/~1v1~1preparation-method~1{Id}'
  /v1/institution:
    $ref: 'institution.yml#/paths/~1v1~1institution'
  /v1/institution/{Id}:
    $ref: 'institution.yml#/paths/~1v1~1institution~1{Id}'
  /v1/storage-unit-type:
    $ref: 'storageUnitType.yml#/paths/~1v1~1storage-unit-type'
  /v1/storage-unit-type/{Id}:
    $ref: 'storageUnitType.yml#/paths/~1v1~1storage-unit-type~1{Id}'
  /v1/acquisition-event:
    $ref: 'acquisitionEvent.yml#/paths/~1v1~1acquisition-event'
  /v1/acquisition-event/{Id}:
    $ref: 'acquisitionEvent.yml#/paths/~1v1~1acquisition-event~1{Id}'
  /v1/project:
    $ref: 'project.yml#/paths/~1v1~1project'
  /v1/project/{Id}:
    $ref: 'project.yml#/paths/~1v1~1project~1{Id}'
  /v1/form-template:
    $ref: 'formTemplate.yml#/paths/~1v1~1form-template'
  /v1/form-template/{Id}:
    $ref: 'formTemplate.yml#/paths/~1v1~1form-template~1{Id}'
  /v1/organism:
    $ref: 'organism.yml#/paths/~1v1~1organism'
  /v1/organism/{Id}:
    $ref: 'organism.yml#/paths/~1v1~1organism~1{Id}'
  /v1/protocol:
    $ref: 'protocol.yml#/paths/~1v1~1protocol'
  /v1/protocol/{Id}:
    $ref: 'protocol.yml#/paths/~1v1~1protocol~1{Id}'
