openapi: 3.0.0
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/AAFC/test/1.0.0
info:
  description: Represents the usage of an object in a storageUnit. May include coordinates (row/column).
  version: "1.0.0"
  title: Storage Unit Usage schema
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /v1/storage-unit-usage:
    get:
      tags:
        - Storage Unit Usage
      summary: Get storage unit usage
      operationId: getStorageUnitUsage
      description: By passing in query string, user can get available storage unit usage authorised
      parameters:
        - in: query
          name: filter[rsql]
          description: pass an optional search string for looking up the storage unit usage
          schema:
            type: string
        - in: query
          name: sort
          description: optional sort order string, such as descending, denoted by "-"
          schema:
            type: string
        - in: query
          name: page[offset]
          description: number of records to skip when paging
          schema:
            type: integer
            format: int32
        - in: query
          name: page[limit]
          description: maximum number of records to return when paging
          schema:
            type: integer
            format: int32
            minimum: 0
            maximum: 50
      responses:
        '200':
          description: storage unit usage satisfying the query restrictions
          content:
            application/vnd.api+json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/StorageUnitUsage'
        '404':
          description: storage unit usage not found
    post:
      tags:
        - Storage Unit Usage
      summary: Add storage unit usage
      operationId: addStorageUnitUsage
      description: Adds a storage unit usage
      responses:
        '201':
          description: storage unit usage created
        '422':
          description: Data integrity violation          
      requestBody:
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/NewStorageUnitUsage'
        description: StorageUnitUsage to add
  /v1/storage-unit-usage/{Id}:
    get:
      tags:
        - Storage Unit Usage
      summary: Find storage unit by ID
      description: Returns a single storage unit usage
      operationId: getStorageUnitUsageById
      parameters:
        - name: Id
          in: path
          description: ID of storage unit usage to return
          required: true
          schema:
            type: string
            format: uuid            
      responses:
        '200':
          description: successful operation
          content:
            application/vnd.api+json:
              schema:          
                $ref: '#/components/schemas/StorageUnitUsage'
        '400':
          description: Not a valid uuid                
        '404':
          description: StorageUnitUsage not found
    patch:
      tags:
        - Storage Unit Usage
      summary: Update storage unit usage
      operationId: updateStorageUnitUsage
      description: update a storage unit usage
      parameters:
        - name: Id
          in: path
          description: storage unit usage id to patch
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: storage unit usage updated
        '400':
          description: invalid input, object invalid
      requestBody:
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/StorageUnitUsage'
        description: storage unit usage to add
    delete:
      tags:
        - Storage Unit Usage
      summary: Delete storage unit usage
      operationId: deleteStorageUnitUsage
      description: delete a storage unit usage
      parameters:
        - name: Id
          in: path
          description: storage unit usage id to delete
          required: true
          schema:
            type: string
            format: uuid            
      responses:
        '200':
          description: storage unit usage deleted
        '400':
          description: Not a valid uuid          
        '404':
          description: storage unit usage not found
components:
  schemas:
    StorageUnitUsage:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
          properties:
            id:
              type: string
              format: uuid
              example: d290f1ee-6c54-4b01-90e6-d701748f0851
              description: Identifier of the object as UUID
          allOf:
            - $ref: '#/components/schemas/CommonStorageUnitUsage'

    NewStorageUnitUsage:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          allOf:
            - $ref: '#/components/schemas/CommonStorageUnitUsage'

    CommonStorageUnitUsage:
      type: object
      required:
        - type
        - attributes       
      properties:            
        type:
          enum: [storage-unit-usage]
          description: The type of data being returned.
        attributes:
          type: object
          properties:
            usageType:
              type: string
              description: The type of the resource using the storage-unit-usage
              example: material-sample
            wellRow:
              type: string
              description: The row location in the storage unit. Using a letter, starting at A.
              example: A
            wellColumn:
              type: number
              description: The column location in the storage unit. Using a number, starting at 1.
              example: 7
            cellNumber:
              type: integer
              description: The calculated cell number based on the storage-unit-type dimension
              readOnly: true
            storageUnitName:
              type: string
              description: The calculated storageUnitName
              readOnly: true
            createdOn:
              type: string
              format: date-time
              readOnly: true
              description: date and time when the storage unit was created in ISO format
              example: 1985-04-12T23:20:50.52Z
            createdBy:
              type: string
              readOnly: true
              description: authenticated user who create the storage unit usage
        relationships:
          type: object
          nullable: false
          properties:
            storageUnit:
              type: object
              description:  Used, if available, to validate the coordinates (row/column) and the group for authorization. If set, storageUnitType should not be used.
              required:
                - data
              properties:
                data:
                  type: object
                  required:
                    - type
                    - id
                  properties:
                    type:
                      enum: [storage-unit]
                    id:
                      type: string
                      format: uuid
                      description: storageUnit's id
                      example: a600f9da-fcbe-4fef-9ae3-0f131ca05e0c
            storageUnitType:
              type: object
              description: Can be used if no specific storageUnit is used. Will be used, if available, to validate the coordinates (row/column) and the group for authorization. If set, storageUnit should not be used.
              required:
                - data
              properties:
                data:
                  type: object
                  required:
                    - type
                    - id
                  properties:
                    type:
                      enum: [storage-unit-type]
                    id:
                      type: string
                      format: uuid
                      description: storageUnitType's id
                      example: 01903c04-036f-7a54-9c44-3df6091fdcc6
