openapi: 3.0.0
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/AAFC/test/1.0.0
info:
  description: Storage Unit Type schema
  version: "1.0.0"
  title: storage unit type schema
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /v1/storage-unit-type:
    get:
      tags:
        - Storage Unit Type
      summary: Get storage unit type
      operationId: getStorageUnitTypes
      description: By passing in query string, user can get available storage unit types authorised
      parameters:
        - $ref: '../components/common-parameters.yml#/FiqlFilter'
        - $ref: '../components/common-parameters.yml#/SimpleSearchFilter'
        - $ref: '../components/common-parameters.yml#/Sort'
        - $ref: '../components/common-parameters.yml#/PageOffset'
        - $ref: '../components/common-parameters.yml#/PageLimit'
      responses:
        '200':
          description: storage unit types satifying the query restrictions
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/StorageUnitTypeResponseList'
        '400':
          description: Bad Request
          content:
            application/vnd.api+json:
              schema:
                $ref: '../components/common-parameters.yml#/BadRequest'
        '404':
          description: storage unit type not found
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/StorageUnitTypeNotFound'
        '410':
          description: Storage unit type deleted
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/StorageUnitTypeDeleted'
    post:
      tags:
        - Storage Unit Type
      summary: Add storage unit type
      operationId: addStorageUnitType
      description: Adds a storage unit type
      responses:
        '201':
          description: storage unit type created
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/StorageUnitTypeResponseWithLink'
        '422':
          description: Data integrity violation
          content:
            application/vnd.api+json:
              schema:
                $ref: '../components/common-parameters.yml#/UnprocessableEntity'
      requestBody:
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/NewStorageUnitType'
        description: StorageUnitType to add
  /v1/storage-unit-type/{Id}:
    get:
      tags:
        - Storage Unit Type
      summary: Find storage unit type by ID
      description: Returns a single storage unit type
      operationId: getStorageUnitTypeById
      parameters:
        - name: Id
          in: path
          description: ID of storage unit type to return
          required: true
          schema:
            type: string
            format: uuid            
      responses:
        '200':
          description: successful operation
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/StorageUnitTypeResponse'
        '400':
          description: Not a valid uuid
          content:
            application/vnd.api+json:
              schema:
                $ref: '../components/common-parameters.yml#/BadRequest'
        '404':
          description: StorageUnitType not found
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/StorageUnitTypeNotFound'
        '410':
          description: Storage unit type deleted
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/StorageUnitTypeDeleted'          
    patch:
      tags:
        - Storage Unit Type
      summary: Update storage unit type
      operationId: updateStorageUnitType
      description: update a storage unit type
      parameters:
        - name: Id
          in: path
          description: storage unit type id to patch
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: storage unit type updated
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/StorageUnitTypeResponse'
        '400':
          description: invalid input, object invalid
          content:
            application/vnd.api+json:
              schema:
                $ref: '../components/common-parameters.yml#/BadRequest'
        '410':
          description: Storage unit type deleted
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/StorageUnitTypeDeleted'
        '422':
          description: Data integrity violation
          content:
            application/vnd.api+json:
              schema:
                $ref: '../components/common-parameters.yml#/UnprocessableEntity'
      requestBody:
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/StorageUnitType'
        description: storage unit type to add
    delete:
      tags:
        - Storage Unit Type
      summary: Delete storage unit type
      operationId: deleteStorageUnitType
      description: delete a storage unit type
      parameters:
        - name: Id
          in: path
          description: storage unit type id to delete
          required: true
          schema:
            type: string
            format: uuid            
      responses:
        '204':
          description: storage unit type marked as deleted
        '400':
          description: Not a valid uuid
          content:
            application/vnd.api+json:
              schema:
                $ref: '../components/common-parameters.yml#/BadRequest'
        '404':
          description: storage unit type not found
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/StorageUnitTypeNotFound'
        '410':
          description: Storage unit type deleted
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/StorageUnitTypeDeleted'       
components:
  schemas:
    StorageUnitTypeResponse:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
          properties:
            id:
              type: string
              format: uuid
              example: d290f1ee-6c54-4b01-90e6-d701748f0851
              description: Identifier of the object as UUID
          allOf:
            - $ref: '#/components/schemas/CommonStorageUnitType'
        meta:
          $ref: '../components/common-parameters.yml#/ResponseMeta'

    StorageUnitTypeResponseList:
      type: object
      required:
        - data
      properties:
        data:
          type: array
          items:
            type: object
            required:
              - id
            properties:
              id:
                type: string
                format: uuid
                example: d290f1ee-6c54-4b01-90e6-d701748f0851
                description: Identifier of the object as UUID
            allOf:
              - $ref: '#/components/schemas/CommonStorageUnitType'
        meta:
          $ref: '../components/common-parameters.yml#/ResponseMeta'

    StorageUnitTypeResponseWithLink:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
          properties:
            id:
              type: string
              format: uuid
              example: d290f1ee-6c54-4b01-90e6-d701748f0851
              description: Identifier of the object as UUID
          allOf:
            - $ref: '#/components/schemas/CommonStorageUnitType'
        links:
          type: object
          properties:
            self:
              type: string
              example: /storage-unit-type/d290f1ee-6c54-4b01-90e6-d701748f0851
            meta:
              type: object
              properties:
                isTemplated:
                  type: boolean
                  example: true
        meta:
          $ref: '../components/common-parameters.yml#/ResponseMeta'

    StorageUnitTypeNotFound:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              status:
                type: string
                enum: ["404"]
                example: "404"
              title:
                type: string
                enum: ["Not Found"]
                example: "Not Found"
              detail:
                type: string
                example: "Storage unit type with ID {id} not found"

    StorageUnitTypeDeleted:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              status:
                type: string
                enum: ["410 GONE"]
                example: "410 GONE"
              title:
                type: string
                enum: ["Gone"]
                example: "Gone"
              detail:
                type: string
                example: "StorageUnitTypeDto with ID 019c055d-a4b7-73a9-912d-03c682715484  Gone. The Resource has been deleted but audit records remain, see the links.about section."
              links:
                type: object
                properties:
                  about:
                    type: string
                    example: "/audit-snapshot?filter[instanceId]=storage-unit-type/{id}"

    StorageUnitType:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
          properties:
            id:
              type: string
              format: uuid
              example: d290f1ee-6c54-4b01-90e6-d701748f0851
              description: Identifier of the object as UUID
          allOf:
            - $ref: '#/components/schemas/CommonStorageUnitType'

    NewStorageUnitType:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          allOf:
            - $ref: '#/components/schemas/CommonStorageUnitType'

    CommonStorageUnitType:
      type: object
      required:
        - type
        - attributes       
      properties:            
        type:
          enum: [storage-unit-type]      
          description: The type of data being returned.
        attributes:
          type: object
          properties:
            name:
              type: string
              description: The name of the storage unit type
            createdBy:
              type: string      
              readOnly: true
              description: authenticated user who create the storage unit type
            createdOn:              
              type: string
              format: date-time                            
              readOnly: true
              description: date and time when the storage unit type was created in ISO format
              example: 1985-04-12T23:20:50.52Z
            group:
              type: string
              description: The group in which the storage unit type belongs to
            isInseperable:
              type: boolean
              description:  Indicates that the content can't be separated without doing a new preparation
            gridLayoutDefinition:
              type: object
              nullable: true
              description: Optional definition of storage type's grid layout (when applicable)
              properties:
                numberOfRows:
                  type: integer
                  minimum: 1
                numberOfColumns:
                  type: integer
                  minimum: 1
                fillDirection:
                  type: string
                  enum: [BY_ROW, BY_COLUMN]
