name: Build and Deploy OpenAPI Specs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: yarn test and build
        run: |
          npx redoc-cli bundle schema/natural-history-collection-api.yml -o redoc/index.html
