@startuml
left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

class "CollectingEvent" as ce {
-dwcVerbatimLatitude
-dwcVerbatimLongitude
-dwcVerbatimLocality
-verbatimEventDateTime
-geographicPlaceNameSource
-collectors
-attachments
}

class "GeographicPlaceNameSourceDetail" as placedetail {
-sourceUrl
-country
-stateProvince
-higherGeographicPlaces
-recordedOn
}

class "GeoreferenceAssertion" as georef {
-dwcDecimalLatitude
-dwcDecimalLongitude
-dwcCoordinateUncertaintyInMeters
-georeferencedBy
-dwcGeoreferenceVerificationStatus
}

class "MaterialSample" as ms {
-materialSampleName
-dwcCatalogueNumber[not unique]
-dwcOtherCatalogNumbers
-preparedBy
-preparationDate
}

skinparam linetype spline

class "Determination" as determination{
-scientificName
-determinationDate
}

class "PreparationType" as preparation{
-name
-description
}

class "MaterialSampleType" as materialsampletype{
-name
-description
}

class "StorageUnit" as storageunit{
-name
-type
}

ce "1 " -- "0..*" georef
ce "1 " -- "1" placedetail
ce "0..1 " --- "0..*" ms

skinparam linetype ortho
ms "1 " --- "0..*" determination
ms "0..*" --- "0..1" preparation
ms "0..*" --- "0..1" materialsampletype
ms "0..*" --- "0..1" storageunit
ms -[#red,dashed]-> ms

@enduml
