@startuml
left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

class "CollectingEvent" as ce {
-lat/long
-date
-collectors
}

class "PhysicalEntity" as pe {
-state
-catalogueNumber[not unique]
-organismId
}

class "Observation" as obs {
}

skinparam linetype spline

class "Identification" as identification{
-count
}

class "PreparationProcess" as preparation{
-preparationType
}

ce "1..* " --- "0..*" pe
ce "1 " -- "0..*" obs
skinparam linetype ortho
pe "1 " --- "0..*" identification
pe "1..*" --- "0..*" preparation
pe -[#red,dashed]-> pe
obs "1 " -- "0..*" identification

@enduml
