@startuml
left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

class "Collecting Event" as ce {
-lat/long
-date
-collectors
}

class "Physical Entity" as pe {
-stateHistory
}

class "Observation" as obs {
}

skinparam linetype spline

class "Catalogued Object" as co {
-catalogueNumber
-organismId
}

note "CatalogNumber\nnot unique" as NU

class "Identification" as identification{
-count
}

class "Preparation" as preparation{
-parentPreparation
}

ce "1..* " -- "0..*" pe
ce "1 " -- "0..*" obs
preparation "1 " -- "0..*" co
skinparam linetype ortho
co "1 " - "0..*" identification
pe "1..*" - "0..*" preparation
co -up-> NU
preparation -[#red,dashed]-> preparation
obs "1 " -- "0..*" identification

legend right
Notable model constraints:
 - Physical Entity Sample is always created even if the user has no data for it
 - Preparation is used to move from Physical Entity to Catalogued Object
 - CataloguedObject + Identification = occurrenceId

endlegend
@enduml
